FROM mysql:8.0-debian

# Install SSH
RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd

# Set root password
RUN echo "root:root" | chpasswd

# Enable password login for root
RUN sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose SSH
EXPOSE 22

# Run both MySQL and SSH
CMD service ssh start && docker-entrypoint.sh mysqld
