version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  client:
    build: .
    depends_on:
      - mysql

